name: spectrome
dependencies:
  - python=3 #or any python 3 should work
  - pip
  - matplotlib
  - numpy
  - scipy
  - pandas
  - nose # for unit testing
  - nodejs==11.9.0
  - ipywidgets
  - pip:
    - pysurfer
    - nibabel
    - deepdish
    - python-csv
    - nitime
    - emcee==3.0rc2
    - tqdm==4.30.0
    - mayavi
    - PyQt5

