name: spectrome
dependencies:
  - python=3.6.6 #or any python 3 should work
  - matplotlib
  - numpy
  - scipy
  - pandas
  - nose # for unit testing
  - h5py==2.9.0
  - ipywidgets
  - vtk==8.1.1
  - pip:
    - pysurfer
    - nibabel
    - deepdish
    - python-csv
    - nitime
    - re
    - emcee==3.0rc2
    - tqdm==4.30.0
    - mayavi
    - PyQt5

